# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2bd4c24f5d2daaceca528ecf90c147c98c54b94c79a4b43b6365d3bc30088094e32c1e639a400159271e5594353753b023812a4731b4f29bd00f32db9b7c20c

test:
  secret_key_base: e2331328ff53fe81570d6e47111bfaa3aef5a3d9640738aa7b5c5641412b92a264ad2a33d7e795a69ae8910a69cec7e756583191d8adcde3d0cc7cfc6e2149f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
